import type { Ingredient, Recipe } from './recipes'

const PANTRY: Record<string, true> = { sól: true, pieprz: true, oliwa: true, olej: true }

function ing(input: Omit<Ingredient, 'pantry'> & { pantry?: boolean }): Ingredient {
  return { ...input, pantry: input.pantry ?? PANTRY[input.key] === true }
}

const regionalRecipeEntries: Recipe[] = [
  {
    slug: 'fattoush-granat',
    title: 'Fattoush z granatem',
    time: '18 min',
    minutes: 18,
    mood: 'fresh',
    cuisine: 'libańska',
    tag: 'crisp salad',
    image: '/recipes/fattoush-granat.webp',
    intro: 'Chrupiąca sałata, ogórek, pomidor, pita i sumak. Granat robi kwaśno-słodki finał, bez którego ta miska byłaby tylko sałatką z charakterem na pół gwizdka.',
    whenToMake: 'Do grilla, do pieczonego kurczaka albo wtedy, gdy chcesz świeżości, ale nie chcesz jeść smutnych liści.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'budżetowo'],
    collections: ['15-min', 'wiosna'],
    ingredients: [
      ing({ amount: 1, name: 'sałata rzymska', key: 'sałata', scalable: true }),
      ing({ amount: 1, name: 'ogórek', key: 'ogórek', scalable: true }),
      ing({ amount: 2, name: 'pomidory', key: 'pomidor', scalable: true }),
      ing({ amount: 1, name: 'pita', key: 'pita', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'ziaren granatu', key: 'granat', scalable: true }),
      ing({ name: 'sumak', key: 'sumak', scalable: false }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Porwij sałatę, pokrój ogórka i pomidory.',
      'Pitę podpiecz na chrupko i połam na kawałki.',
      'Wymieszaj warzywa z oliwą, sumakiem i solą.',
      'Dodaj pitę oraz granat tuż przed podaniem.',
    ],
    stepImages: [
      '/recipes/steps/fattoush-granat-step-1.webp',
      '/recipes/steps/fattoush-granat-step-2.webp',
      '/recipes/steps/fattoush-granat-step-3.webp',
      '/recipes/steps/fattoush-granat-step-4.webp',
    ],
    tip: 'Pita ma chrupać. Jeśli dodasz ją za wcześnie, zrobi się mokry kartonik.',
  },
  {
    slug: 'tabbouleh-mieta-cytryna',
    title: 'Tabbouleh z miętą i cytryną',
    time: '20 min',
    minutes: 20,
    mood: 'fresh',
    cuisine: 'libańska',
    tag: 'herb bomb',
    image: '/recipes/tabbouleh-mieta-cytryna.webp',
    intro: 'To nie jest kasza z pietruszką, tylko pietruszka z odrobiną bulguru. Cytryna, mięta i pomidor robią świeżą miskę, która budzi stół.',
    whenToMake: 'Kiedy ciężkie danie potrzebuje lekkiego kontrapunktu albo lodówka mówi: mam zioła, użyj ich zanim skapitulują.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'budżetowo'],
    collections: ['wiosna', 'meal-prep'],
    ingredients: [
      ing({ amount: 2, unit: 'pęczki', name: 'natki pietruszki', key: 'pietruszka', scalable: true }),
      ing({ amount: 40, unit: 'g', name: 'drobnego bulguru', key: 'bulgur', scalable: true }),
      ing({ amount: 2, name: 'pomidory', key: 'pomidor', scalable: true }),
      ing({ amount: 0.5, name: 'cytryny', key: 'cytryna', scalable: true }),
      ing({ name: 'mięta', key: 'mięta', scalable: false }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Zalej bulgur wrzątkiem i odstaw, aż zmięknie.',
      'Posiekaj natkę bardzo drobno, bez lenistwa.',
      'Dodaj pomidory, miętę, cytrynę i oliwę.',
      'Wymieszaj z bulgurem i dopraw solą.',
    ],
    tip: 'Jeśli w misce dominuje bulgur, to już nie tabbouleh, tylko sałatka kaszowa w przebraniu.',
  },
  {
    slug: 'kibbeh-z-piekarnika',
    title: 'Kibbeh z piekarnika',
    time: '45 min',
    minutes: 45,
    mood: 'comfort',
    cuisine: 'libańska',
    tag: 'baked comfort',
    image: '/recipes/kibbeh-z-piekarnika.webp',
    intro: 'Warstwa bulguru z wołowiną, środek z cebulą i przyprawami, a na górze rumiane romby. Domowy comfort, tylko bardziej pachnący niż zwykła zapiekanka.',
    whenToMake: 'Na gości albo meal-prep, gdy chcesz coś konkretnego, co dobrze kroi się na porcje.',
    servings: 4,
    effort: 'więcej ruchów',
    dietTags: ['high-protein', 'comfort'],
    collections: ['na-gosci', 'meal-prep'],
    ingredients: [
      ing({ amount: 300, unit: 'g', name: 'mielonej wołowiny', key: 'wołowina', scalable: true }),
      ing({ amount: 150, unit: 'g', name: 'drobnego bulguru', key: 'bulgur', scalable: true }),
      ing({ amount: 1, name: 'cebula', key: 'cebula', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'baharatu', key: 'baharat', scalable: true }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
      ing({ name: 'sól', key: 'sól', scalable: false }),
    ],
    steps: [
      'Namocz bulgur, potem odciśnij go porządnie.',
      'Połącz część mięsa z bulgurem i przyprawami.',
      'Podsmaż cebulę z resztą mięsa na nadzienie.',
      'Ułóż warstwy w formie, natnij romby i piecz do zrumienienia.',
    ],
    tip: 'Nacięcia przed pieczeniem nie są dekoracją dla dekoracji. Dzięki nim oliwa wchodzi w środek.',
  },
  {
    slug: 'manakish-zaatar',
    title: 'Manakish z zaatarem',
    time: '30 min',
    minutes: 30,
    mood: 'brunch',
    cuisine: 'libańska',
    tag: 'flatbread',
    image: '/recipes/manakish-zaatar.webp',
    intro: 'Cienki placek, oliwa i zaatar. Minimalizm, który pachnie jak piekarnia, a nie jak szybka tortilla z przyprawą.',
    whenToMake: 'Na leniwe śniadanie, do labneh albo jako szybki stół do dzielenia.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'budżetowo'],
    collections: ['na-gosci', 'na-gosci'],
    ingredients: [
      ing({ amount: 250, unit: 'g', name: 'ciasta na pizzę', key: 'ciasto', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'zaataru', key: 'zaatar', scalable: true }),
      ing({ amount: 3, unit: 'łyżki', name: 'oliwy', key: 'oliwa', scalable: true }),
      ing({ name: 'labneh albo jogurt', key: 'jogurt', scalable: false }),
    ],
    steps: [
      'Rozwałkuj ciasto na cienkie placki.',
      'Wymieszaj zaatar z oliwą na pastę.',
      'Posmaruj placki i piecz bardzo gorąco.',
      'Podaj z jogurtem albo labneh.',
    ],
    tip: 'Nie żałuj oliwy. Suchy zaatar na suchym cieście to pył, nie śniadanie.',
  },
  {
    slug: 'mujaddara-cebula',
    title: 'Mujaddara z chrupiącą cebulą',
    time: '35 min',
    minutes: 35,
    mood: 'comfort',
    cuisine: 'libańska',
    tag: 'pantry hero',
    image: '/recipes/mujaddara-cebula.webp',
    intro: 'Soczewica, ryż i cebula. Brzmi skromnie, ale dobra karmelizacja robi z tego miskę, która ma więcej sensu niż połowa drogich dodatków.',
    whenToMake: 'Gdy chcesz tani obiad, który naprawdę syci i dobrze znosi odgrzewanie.',
    servings: 3,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'budżetowo', 'lunchbox'],
    collections: ['meal-prep', 'po-pracy'],
    ingredients: [
      ing({ amount: 120, unit: 'g', name: 'zielonej soczewicy', key: 'soczewica', scalable: true }),
      ing({ amount: 100, unit: 'g', name: 'ryżu', key: 'ryż', scalable: true }),
      ing({ amount: 3, name: 'cebule', key: 'cebula', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'kuminu', key: 'kumin', scalable: true }),
      ing({ name: 'olej', key: 'olej', scalable: false }),
    ],
    steps: [
      'Ugotuj soczewicę prawie do miękkości.',
      'Dodaj ryż i kumin, gotuj razem do miękkości.',
      'Cebulę smaż długo, aż będzie ciemnozłota.',
      'Podaj miskę z cebulą na górze.',
    ],
    tip: 'Cebula jest tu główną robotą. Blada cebula da blady obiad. Brutalne, ale prawdziwe.',
  },
  {
    slug: 'sayadieh-ryba-ryz',
    title: 'Sayadieh z rybą i ryżem',
    time: '40 min',
    minutes: 40,
    mood: 'comfort',
    cuisine: 'libańska',
    tag: 'fish rice',
    image: '/recipes/sayadieh-ryba-ryz.webp',
    intro: 'Ryż gotowany z cebulą, przyprawami i rybą ma głęboki, morski smak bez kombinowania z sosem przez pół dnia.',
    whenToMake: 'Kiedy masz białą rybę i chcesz pełny obiad z jednego garnka.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['high-protein'],
    collections: ['po-pracy', 'one-pan'],
    ingredients: [
      ing({ amount: 2, name: 'filety białej ryby', key: 'ryba', scalable: true }),
      ing({ amount: 120, unit: 'g', name: 'ryżu', key: 'ryż', scalable: true }),
      ing({ amount: 2, name: 'cebule', key: 'cebula', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'kuminu', key: 'kumin', scalable: true }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
    ],
    steps: [
      'Cebulę podsmaż mocno, aż zrobi bazę smaku.',
      'Dodaj ryż, przyprawy i wodę.',
      'Ułóż rybę na wierzchu pod koniec gotowania.',
      'Podawaj z cytryną i pieprzem.',
    ],
    tip: 'Nie mieszaj ryby jak risotto. Połóż ją, przykryj i daj jej dojść spokojnie.',
  },
  {
    slug: 'batata-harra',
    title: 'Batata harra',
    time: '28 min',
    minutes: 28,
    mood: 'quick',
    cuisine: 'libańska',
    tag: 'spicy potatoes',
    image: '/recipes/batata-harra.webp',
    intro: 'Ziemniaki z chilli, czosnkiem, kolendrą i cytryną. Niby dodatek, ale potrafi ukraść cały stół.',
    whenToMake: 'Do mezze, do jajek albo jako szybka kolacja z jogurtem.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'budżetowo'],
    collections: ['po-pracy', 'one-pan'],
    ingredients: [
      ing({ amount: 500, unit: 'g', name: 'ziemniaków', key: 'ziemniaki', scalable: true }),
      ing({ amount: 2, unit: 'ząbki', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ name: 'kolendra', key: 'kolendra', scalable: false }),
      ing({ name: 'chilli', key: 'chilli', scalable: false }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Pokrój ziemniaki i upiecz albo usmaż do złotych brzegów.',
      'Na patelni podgrzej oliwę z czosnkiem i chilli.',
      'Wrzuć ziemniaki, kolendrę i sok z cytryny.',
      'Dopraw solą i podaj gorące.',
    ],
    tip: 'Cytryna na końcu robi różnicę. Bez niej to tylko ostre ziemniaki, czyli połowa zabawy.',
  },
  {
    slug: 'kousa-mahshi',
    title: 'Kousa mahshi',
    time: '55 min',
    minutes: 55,
    mood: 'comfort',
    cuisine: 'libańska',
    tag: 'stuffed veg',
    image: '/recipes/kousa-mahshi.webp',
    intro: 'Małe cukinie faszerowane ryżem i mięsem, duszone w pomidorach. Domowe, miękkie, trochę cierpliwe, ale bez restauracyjnego napięcia.',
    whenToMake: 'Na weekendowy garnek, kiedy obiad ma pachnieć domem i dać resztki na jutro.',
    servings: 4,
    effort: 'więcej ruchów',
    dietTags: ['comfort', 'lunchbox'],
    collections: ['meal-prep', 'rozgrzewa'],
    ingredients: [
      ing({ amount: 6, name: 'małych cukinii', key: 'cukinia', scalable: true }),
      ing({ amount: 160, unit: 'g', name: 'mielonej wołowiny', key: 'wołowina', scalable: true }),
      ing({ amount: 80, unit: 'g', name: 'ryżu', key: 'ryż', scalable: true }),
      ing({ amount: 500, unit: 'ml', name: 'passaty', key: 'passata', scalable: true }),
      ing({ name: 'baharat', key: 'baharat', scalable: false }),
    ],
    steps: [
      'Wydrąż cukinie, zostawiając cienkie ścianki.',
      'Wymieszaj mięso, ryż i przyprawy.',
      'Napełnij cukinie luźno, bo ryż urośnie.',
      'Duś w passacie, aż ryż i cukinia będą miękkie.',
    ],
    tip: 'Nie upychaj farszu jak walizki na lotnisko. Ryż potrzebuje miejsca.',
  },
  {
    slug: 'shawarma-kurczak-talerz',
    title: 'Shawarma z kurczaka na talerzu',
    time: '32 min',
    minutes: 32,
    mood: 'comfort',
    cuisine: 'libańska',
    tag: 'weeknight shawarma',
    image: '/recipes/shawarma-kurczak-talerz.webp',
    intro: 'Jogurt, czosnek, kumin i papryka robią szybki kierunek shawarmy bez pionowego rożna w mieszkaniu. Rozsądnie.',
    whenToMake: 'Gdy chcesz kebabowy vibe, ale talerz ma być trochę bardziej ogarnięty.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['high-protein', 'comfort'],
    collections: ['po-pracy'],
    ingredients: [
      ing({ amount: 350, unit: 'g', name: 'udek z kurczaka', key: 'kurczak', scalable: true }),
      ing({ amount: 3, unit: 'łyżki', name: 'jogurtu', key: 'jogurt', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'kuminu', key: 'kumin', scalable: true }),
      ing({ amount: 1, unit: 'ząbek', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ name: 'pita', key: 'pita', scalable: false }),
      ing({ name: 'ogórek', key: 'ogórek', scalable: false }),
    ],
    steps: [
      'Wymieszaj jogurt, czosnek, kumin, paprykę i sól.',
      'Obtocz kurczaka i odstaw choć na 10 minut.',
      'Usmaż albo upiecz do mocnych brzegów.',
      'Podaj z pitą, ogórkiem i sosem jogurtowym.',
    ],
    tip: 'Najlepszy smak jest na przypieczonych krawędziach. Blady kurczak tu nie ma argumentów.',
  },
  {
    slug: 'muhallabieh-pistacje',
    title: 'Muhallabieh z pistacjami',
    time: '20 min + chłodzenie',
    minutes: 20,
    mood: 'brunch',
    cuisine: 'libańska',
    tag: 'milk pudding',
    image: '/recipes/muhallabieh-pistacje.webp',
    intro: 'Delikatny mleczny pudding z wodą różaną i pistacjami. Słodki, lekki, bez ciężaru ciasta po obiedzie.',
    whenToMake: 'Po ostrym albo ciężkim jedzeniu, gdy deser ma uspokoić stół.',
    servings: 4,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'bez glutenu'],
    collections: ['na-gosci', 'meal-prep'],
    ingredients: [
      ing({ amount: 500, unit: 'ml', name: 'mleka', key: 'mleko', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'skrobi kukurydzianej', key: 'skrobia', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'cukru', key: 'cukier', scalable: true }),
      ing({ name: 'woda różana', key: 'woda różana', scalable: false, optional: true }),
      ing({ name: 'pistacje', key: 'pistacje', scalable: false }),
    ],
    steps: [
      'Wymieszaj mleko, skrobię i cukier na zimno.',
      'Gotuj, mieszając, aż masa zgęstnieje.',
      'Dodaj odrobinę wody różanej.',
      'Przelej do miseczek i schłódź z pistacjami.',
    ],
    tip: 'Z wodą różaną ostrożnie. Jedna kropla za dużo i deser idzie w mydło babci.',
  },
  {
    slug: 'menemen-papryka',
    title: 'Menemen z papryką',
    time: '18 min',
    minutes: 18,
    mood: 'brunch',
    cuisine: 'turecka',
    tag: 'eggs skillet',
    image: '/recipes/menemen-papryka.webp',
    intro: 'Jajka ścięte w pomidorach i papryce, miękkie, soczyste i idealne do wycierania chlebem.',
    whenToMake: 'Na śniadanie, brunch albo kolację, kiedy jajka mają zrobić coś więcej niż dyżurową jajecznicę.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'budżetowo'],
    collections: ['15-min', 'one-pan'],
    ingredients: [
      ing({ amount: 3, name: 'jajka', key: 'jajko', scalable: true }),
      ing({ amount: 2, name: 'pomidory', key: 'pomidor', scalable: true }),
      ing({ amount: 1, name: 'zielona papryka', key: 'papryka', scalable: true }),
      ing({ name: 'chilli', key: 'chilli', scalable: false }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Podsmaż paprykę na oliwie.',
      'Dodaj pomidory i gotuj, aż zrobią sos.',
      'Wbij jajka i mieszaj krótko.',
      'Zdejmij, gdy jajka są jeszcze kremowe.',
    ],
    stepImages: [
      '/recipes/steps/menemen-papryka-step-1.webp',
      '/recipes/steps/menemen-papryka-step-2.webp',
      '/recipes/steps/menemen-papryka-step-3.webp',
      '/recipes/steps/menemen-papryka-step-4.webp',
    ],
    tip: 'Nie przesusz jajek. Menemen ma być soczysty, nie grudkowany jak stołówkowy dramat.',
  },
  {
    slug: 'mercimek-corbasi',
    title: 'Mercimek corbasi',
    time: '30 min',
    minutes: 30,
    mood: 'soup',
    cuisine: 'turecka',
    tag: 'lentil soup',
    image: '/recipes/mercimek-corbasi.webp',
    intro: 'Czerwona soczewica, cebula i cytryna. Gęsta turecka zupa, która robi pełny obiad z kilku prostych składników.',
    whenToMake: 'Gdy chcesz miskę ciepła bez rosołowego ceremoniału.',
    servings: 3,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'budżetowo'],
    collections: ['rozgrzewa', 'meal-prep'],
    ingredients: [
      ing({ amount: 180, unit: 'g', name: 'czerwonej soczewicy', key: 'soczewica', scalable: true }),
      ing({ amount: 1, name: 'cebula', key: 'cebula', scalable: true }),
      ing({ amount: 1, name: 'marchewka', key: 'marchew', scalable: true }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
      ing({ name: 'papryka', key: 'papryka', scalable: false }),
    ],
    steps: [
      'Podsmaż cebulę i marchew.',
      'Dodaj soczewicę, wodę i sól.',
      'Gotuj do rozpadu soczewicy.',
      'Zblenduj i podaj z cytryną oraz papryką.',
    ],
    tip: 'Cytryna na talerzu jest obowiązkowa. Bez niej zupa jest poprawna, a poprawność to nuda.',
  },
  {
    slug: 'kisir-granat',
    title: 'Kisir z granatem',
    time: '25 min',
    minutes: 25,
    mood: 'fresh',
    cuisine: 'turecka',
    tag: 'bulgur salad',
    image: '/recipes/kisir-granat.webp',
    intro: 'Bulgur z pastą paprykową, ziołami, cytryną i granatem. Sycący, ale świeży, czyli bardzo dobry lunchbox.',
    whenToMake: 'Do pudełka, na stół mezze albo gdy sałatka ma realnie nakarmić.',
    servings: 3,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'lunchbox'],
    collections: ['meal-prep', 'wiosna'],
    ingredients: [
      ing({ amount: 160, unit: 'g', name: 'drobnego bulguru', key: 'bulgur', scalable: true }),
      ing({ amount: 1, unit: 'łyżka', name: 'pasty paprykowej', key: 'pasta paprykowa', scalable: true }),
      ing({ name: 'natka', key: 'pietruszka', scalable: false }),
      ing({ name: 'granat', key: 'granat', scalable: false }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
    ],
    steps: [
      'Zalej bulgur wrzątkiem i przykryj.',
      'Wmieszaj pastę paprykową, oliwę i cytrynę.',
      'Dodaj zioła oraz granat.',
      'Dopraw i odstaw na kilka minut.',
    ],
    tip: 'Kisir lubi odpoczynek. Po 10 minutach smak jest dwa razy bardziej poukładany.',
  },
  {
    slug: 'imam-bayildi',
    title: 'Imam bayildi',
    time: '50 min',
    minutes: 50,
    mood: 'comfort',
    cuisine: 'turecka',
    tag: 'silky eggplant',
    image: '/recipes/imam-bayildi.webp',
    intro: 'Bakłażan duszony z cebulą, pomidorem i oliwą aż robi się jedwabisty. Zero mięsa, dużo charakteru.',
    whenToMake: 'Kiedy bakłażan ma być głównym daniem, nie dekoracją obok mięsa.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'comfort'],
    collections: ['na-gosci', 'wiosna'],
    ingredients: [
      ing({ amount: 2, name: 'bakłażany', key: 'bakłażan', scalable: true }),
      ing({ amount: 2, name: 'cebule', key: 'cebula', scalable: true }),
      ing({ amount: 3, name: 'pomidory', key: 'pomidor', scalable: true }),
      ing({ amount: 2, unit: 'ząbki', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Natnij bakłażany i podsmaż je na oliwie.',
      'Cebulę, czosnek i pomidory duś na miękko.',
      'Napełnij bakłażany farszem.',
      'Duś albo piecz, aż będą bardzo miękkie.',
    ],
    tip: 'Bakłażan musi dostać oliwę. Dietetyczna wersja będzie smutna i gumowa.',
  },
  {
    slug: 'manti-jogurt',
    title: 'Manti z jogurtem',
    time: '50 min',
    minutes: 50,
    mood: 'comfort',
    cuisine: 'turecka',
    tag: 'tiny dumplings',
    image: '/recipes/manti-jogurt.webp',
    intro: 'Małe pierożki z mięsem, czosnkowy jogurt i masło z papryką. Trochę pracy, ale nagroda jest konkretna.',
    whenToMake: 'Na weekend albo wieczór, kiedy chcesz dłubać przy stole i mieć z tego coś lepszego niż scrollowanie.',
    servings: 3,
    effort: 'więcej ruchów',
    dietTags: ['comfort', 'high-protein'],
    collections: ['na-gosci'],
    ingredients: [
      ing({ amount: 250, unit: 'g', name: 'ciasta pierogowego', key: 'ciasto', scalable: true }),
      ing({ amount: 180, unit: 'g', name: 'mielonej wołowiny', key: 'wołowina', scalable: true }),
      ing({ amount: 200, unit: 'g', name: 'jogurtu', key: 'jogurt', scalable: true }),
      ing({ amount: 1, unit: 'ząbek', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ name: 'masło i papryka', key: 'masło', scalable: false }),
    ],
    steps: [
      'Farsz dopraw solą, pieprzem i cebulą.',
      'Lep małe pierożki i gotuj je w osolonej wodzie.',
      'Wymieszaj jogurt z czosnkiem.',
      'Polej manti jogurtem i masłem z papryką.',
    ],
    tip: 'Manti mają być małe. Duże robią się zwykłymi pierogami z tureckim PR-em.',
  },
  {
    slug: 'lahmacun-szybki',
    title: 'Szybki lahmacun',
    time: '28 min',
    minutes: 28,
    mood: 'quick',
    cuisine: 'turecka',
    tag: 'thin flatbread',
    image: '/recipes/lahmacun-szybki.webp',
    intro: 'Cienki placek z pikantnym mięsem, pietruszką i cytryną. Rolujesz, zjadasz, zero sztućców, dużo sensu.',
    whenToMake: 'Kiedy pizza byłaby za ciężka, a wrap za nudny.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['high-protein'],
    collections: ['po-pracy'],
    ingredients: [
      ing({ amount: 2, name: 'cienkie placki', key: 'tortilla', scalable: true }),
      ing({ amount: 160, unit: 'g', name: 'mielonej jagnięciny albo wołowiny', key: 'wołowina', scalable: true }),
      ing({ amount: 1, unit: 'łyżka', name: 'pasty paprykowej', key: 'pasta paprykowa', scalable: true }),
      ing({ name: 'pietruszka', key: 'pietruszka', scalable: false }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
    ],
    steps: [
      'Wymieszaj mięso z pastą paprykową i przyprawami.',
      'Rozsmaruj cienko na plackach.',
      'Piecz krótko w bardzo gorącym piekarniku.',
      'Podaj z pietruszką i cytryną.',
    ],
    tip: 'Warstwa mięsa ma być cienka. Gruba zrobi klops na podpłomyku.',
  },
  {
    slug: 'cilbir-jajka',
    title: 'Cilbir',
    time: '18 min',
    minutes: 18,
    mood: 'brunch',
    cuisine: 'turecka',
    tag: 'yogurt eggs',
    image: '/recipes/cilbir-jajka.webp',
    intro: 'Jajka w koszulkach na czosnkowym jogurcie, masło z papryką na górze. Brunch, który wygląda luksusowo, a robi się z lodówki.',
    whenToMake: 'Gdy chcesz śniadanie z efektem „o proszę”, bez kolejki po croissanta.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'high-protein', 'bez glutenu'],
    collections: ['15-min', 'na-gosci'],
    ingredients: [
      ing({ amount: 2, name: 'jajka', key: 'jajko', scalable: true }),
      ing({ amount: 200, unit: 'g', name: 'jogurtu greckiego', key: 'jogurt', scalable: true }),
      ing({ amount: 1, unit: 'ząbek', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ amount: 1, unit: 'łyżka', name: 'masła', key: 'masło', scalable: true }),
      ing({ name: 'papryka pul biber', key: 'chilli', scalable: false }),
    ],
    steps: [
      'Wymieszaj jogurt z czosnkiem i solą.',
      'Ugotuj jajka w koszulkach.',
      'Rozpuść masło z papryką.',
      'Połóż jajka na jogurcie i polej masłem.',
    ],
    tip: 'Jogurt nie może być lodowaty. Daj mu chwilę poza lodówką, inaczej kontrast będzie zbyt agresywny.',
  },
  {
    slug: 'pide-ser-szpinak',
    title: 'Pide z serem i szpinakiem',
    time: '35 min',
    minutes: 35,
    mood: 'comfort',
    cuisine: 'turecka',
    tag: 'boat bread',
    image: '/recipes/pide-ser-szpinak.webp',
    intro: 'Łódka z ciasta, słony ser i szpinak. Proste, ciepłe i dużo bardziej obiadowe niż zwykła kanapka z piekarnika.',
    whenToMake: 'Na wieczór filmowy albo kolację, którą można kroić na kawałki i podjadać.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'comfort'],
    collections: ['po-pracy', 'na-gosci'],
    ingredients: [
      ing({ amount: 250, unit: 'g', name: 'ciasta na pizzę', key: 'ciasto', scalable: true }),
      ing({ amount: 150, unit: 'g', name: 'szpinaku', key: 'szpinak', scalable: true }),
      ing({ amount: 100, unit: 'g', name: 'beyaz peynir albo fety', key: 'feta', scalable: true }),
      ing({ amount: 1, name: 'jajko', key: 'jajko', scalable: true, optional: true }),
    ],
    steps: [
      'Podsmaż szpinak i odciśnij nadmiar wody.',
      'Rozwałkuj ciasto w owal.',
      'Nałóż ser i szpinak, zawiń brzegi.',
      'Piecz do złotych krawędzi.',
    ],
    tip: 'Odciśnij szpinak. Mokry farsz zamieni pide w łódkę ratunkową.',
  },
  {
    slug: 'kofte-sumak-cebula',
    title: 'Kofte z cebulą sumakową',
    time: '30 min',
    minutes: 30,
    mood: 'comfort',
    cuisine: 'turecka',
    tag: 'spiced meatballs',
    image: '/recipes/kofte-sumak-cebula.webp',
    intro: 'Małe kotleciki z kuminem i pietruszką, podane z ostrą cebulą w sumaku. Konkret, ale z kwaśnym przełamaniem.',
    whenToMake: 'Na szybki obiad z ryżem, pitą albo sałatą.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['high-protein', 'comfort'],
    collections: ['po-pracy', 'one-pan'],
    ingredients: [
      ing({ amount: 300, unit: 'g', name: 'mielonej wołowiny', key: 'wołowina', scalable: true }),
      ing({ amount: 1, name: 'cebula', key: 'cebula', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'kuminu', key: 'kumin', scalable: true }),
      ing({ name: 'pietruszka', key: 'pietruszka', scalable: false }),
      ing({ name: 'sumak', key: 'sumak', scalable: false }),
    ],
    steps: [
      'Wymieszaj mięso z kuminem, solą i pietruszką.',
      'Uformuj małe kotleciki.',
      'Smaż na mocno rozgrzanej patelni.',
      'Podaj z cebulą wymieszaną z sumakiem.',
    ],
    tip: 'Nie maltretuj mięsa przy mieszaniu. Kofte mają być sprężyste, nie gumowe.',
  },
  {
    slug: 'sutlac-wanilia',
    title: 'Sutlac z wanilią',
    time: '35 min',
    minutes: 35,
    mood: 'brunch',
    cuisine: 'turecka',
    tag: 'rice pudding',
    image: '/recipes/sutlac-wanilia.webp',
    intro: 'Ryżowy pudding mleczny, kremowy i spokojny, z przypieczoną górą albo cynamonem. Deser bez kombinowania.',
    whenToMake: 'Po ostrym jedzeniu albo wtedy, gdy chcesz deser z garnka, nie cały projekt cukierniczy.',
    servings: 4,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'bez glutenu', 'dla dzieci'],
    collections: ['meal-prep'],
    ingredients: [
      ing({ amount: 80, unit: 'g', name: 'ryżu', key: 'ryż', scalable: true }),
      ing({ amount: 700, unit: 'ml', name: 'mleka', key: 'mleko', scalable: true }),
      ing({ amount: 3, unit: 'łyżki', name: 'cukru', key: 'cukier', scalable: true }),
      ing({ name: 'wanilia', key: 'wanilia', scalable: false }),
      ing({ name: 'cynamon', key: 'cynamon', scalable: false }),
    ],
    steps: [
      'Podgotuj ryż w małej ilości wody.',
      'Dodaj mleko, cukier i wanilię.',
      'Gotuj powoli, aż pudding zgęstnieje.',
      'Schłódź albo zapiecz krótko pod grillem.',
    ],
    tip: 'Mieszaj przy końcu. Mleko przypala się dokładnie wtedy, kiedy uznasz, że masz chwilę.',
  },
  {
    slug: 'sabich-baklazan',
    title: 'Sabich z bakłażanem',
    time: '35 min',
    minutes: 35,
    mood: 'comfort',
    cuisine: 'izraelska',
    tag: 'loaded pita',
    image: '/recipes/sabich-baklazan.webp',
    intro: 'Pita z bakłażanem, jajkiem, tahini i świeżymi warzywami. Brzmi jak kanapka, je się jak pełny obiad.',
    whenToMake: 'Gdy masz pitę i chcesz coś konkretnego bez mięsa.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'comfort'],
    collections: ['po-pracy'],
    ingredients: [
      ing({ amount: 2, name: 'pity', key: 'pita', scalable: true }),
      ing({ amount: 1, name: 'bakłażan', key: 'bakłażan', scalable: true }),
      ing({ amount: 2, name: 'jajka', key: 'jajko', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'tahini', key: 'tahini', scalable: true }),
      ing({ name: 'ogórek i pomidor', key: 'ogórek', scalable: false }),
    ],
    steps: [
      'Usmaż albo upiecz plastry bakłażana.',
      'Ugotuj jajka na twardo.',
      'Wymieszaj tahini z cytryną i wodą.',
      'Napełnij pity warzywami, jajkiem, bakłażanem i sosem.',
    ],
    stepImages: [
      '/recipes/steps/sabich-baklazan-step-1.webp',
      '/recipes/steps/sabich-baklazan-step-2.webp',
      '/recipes/steps/sabich-baklazan-step-3.webp',
      '/recipes/steps/sabich-baklazan-step-4.webp',
    ],
    tip: 'Bakłażan musi być miękki w środku. Półsurowy robi z sabicha ćwiczenie szczęki.',
  },
  {
    slug: 'shakshuka-harissa',
    title: 'Shakshuka z harissą',
    time: '24 min',
    minutes: 24,
    mood: 'brunch',
    cuisine: 'izraelska',
    tag: 'spicy eggs',
    image: '/recipes/shakshuka-harissa.webp',
    intro: 'Jajka w sosie pomidorowym z harissą, papryką i kuminem. Klasyk, który wybacza pustą lodówkę.',
    whenToMake: 'Na brunch, szybką kolację albo dzień, gdy chcesz jeść prosto z patelni.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'budżetowo', 'bez glutenu'],
    collections: ['po-pracy', 'one-pan'],
    ingredients: [
      ing({ amount: 4, name: 'jajka', key: 'jajko', scalable: true }),
      ing({ amount: 1, unit: 'puszka', name: 'pomidorów', key: 'pomidor', scalable: true }),
      ing({ amount: 1, name: 'papryka', key: 'papryka', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'harissy', key: 'harissa', scalable: true }),
      ing({ name: 'kumin', key: 'kumin', scalable: false }),
    ],
    steps: [
      'Podsmaż paprykę z kuminem.',
      'Dodaj pomidory i harissę, gotuj do zgęstnienia.',
      'Zrób wgłębienia i wbij jajka.',
      'Przykryj, aż białka się zetną.',
    ],
    tip: 'Sos ma być gęsty przed jajkami. Wodnista shakshuka to jajka na pomidorowym jeziorze.',
  },
  {
    slug: 'jerusalem-mixed-grill',
    title: 'Jerusalem mixed grill',
    time: '35 min',
    minutes: 35,
    mood: 'comfort',
    cuisine: 'izraelska',
    tag: 'spiced chicken',
    image: '/recipes/jerusalem-mixed-grill.webp',
    intro: 'Kurczak z cebulą, kuminem, kurkumą i pieprzem. Szybki, mocno przyprawiony talerz do pity albo ryżu.',
    whenToMake: 'Gdy chcesz mięso z patelni, ale nie kolejną nudną pierś.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['high-protein', 'comfort'],
    collections: ['po-pracy', 'one-pan'],
    ingredients: [
      ing({ amount: 350, unit: 'g', name: 'udek z kurczaka', key: 'kurczak', scalable: true }),
      ing({ amount: 1, name: 'cebula', key: 'cebula', scalable: true }),
      ing({ amount: 1, unit: 'łyżeczka', name: 'kuminu', key: 'kumin', scalable: true }),
      ing({ name: 'kurkuma', key: 'kurkuma', scalable: false }),
      ing({ name: 'pita', key: 'pita', scalable: false }),
    ],
    steps: [
      'Pokrój kurczaka w małe kawałki.',
      'Podsmaż cebulę, dodaj przyprawy.',
      'Wrzuć kurczaka i smaż mocno, aż złapie brzegi.',
      'Podaj w picie albo z ryżem.',
    ],
    tip: 'Małe kawałki oznaczają więcej przypieczonych krawędzi. Matematyka w służbie obiadu.',
  },
  {
    slug: 'malabi-roza-pistacje',
    title: 'Malabi z różą i pistacjami',
    time: '18 min + chłodzenie',
    minutes: 18,
    mood: 'brunch',
    cuisine: 'izraelska',
    tag: 'silky pudding',
    image: '/recipes/malabi-roza-pistacje.webp',
    intro: 'Mleczny pudding z syropem różanym, pistacjami i lekką słodyczą. Prosty deser, który wygląda jak więcej pracy niż jest.',
    whenToMake: 'Na koniec kolacji, szczególnie po czymś pikantnym.',
    servings: 4,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'bez glutenu'],
    collections: ['na-gosci', 'meal-prep'],
    ingredients: [
      ing({ amount: 500, unit: 'ml', name: 'mleka', key: 'mleko', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'skrobi', key: 'skrobia', scalable: true }),
      ing({ name: 'syrop różany', key: 'syrop różany', scalable: false }),
      ing({ name: 'pistacje', key: 'pistacje', scalable: false }),
    ],
    steps: [
      'Wymieszaj mleko ze skrobią i cukrem.',
      'Gotuj, aż zgęstnieje.',
      'Przelej do misek i schłódź.',
      'Podaj z syropem różanym i pistacjami.',
    ],
    tip: 'Syrop dodaj na zimno, nie do garnka. Inaczej aromat odleci szybciej niż cierpliwość.',
  },
  {
    slug: 'ptitim-warzywa',
    title: 'Ptitim z warzywami',
    time: '25 min',
    minutes: 25,
    mood: 'quick',
    cuisine: 'izraelska',
    tag: 'pearl pasta',
    image: '/recipes/ptitim-warzywa.webp',
    intro: 'Izraelski kuskus z warzywami, ziołami i cytryną. Szybki garnek, który dobrze robi za lunchbox.',
    whenToMake: 'Kiedy chcesz coś między makaronem, kaszą i sałatką na ciepło.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'lunchbox', 'dla dzieci'],
    collections: ['po-pracy', 'meal-prep'],
    ingredients: [
      ing({ amount: 160, unit: 'g', name: 'ptitim', key: 'ptitim', scalable: true }),
      ing({ amount: 1, name: 'cukinia', key: 'cukinia', scalable: true }),
      ing({ amount: 1, name: 'marchewka', key: 'marchew', scalable: true }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
      ing({ name: 'natka', key: 'pietruszka', scalable: false }),
    ],
    steps: [
      'Podsmaż warzywa na oliwie.',
      'Dodaj ptitim i chwilę podpraż.',
      'Wlej wodę, gotuj pod przykryciem.',
      'Dopraw cytryną i natką.',
    ],
    tip: 'Podpraż ptitim przed wodą. Ten mały krok robi smak bardziej orzechowy.',
  },
  {
    slug: 'schnitzel-sezam',
    title: 'Schnitzel z sezamem',
    time: '28 min',
    minutes: 28,
    mood: 'comfort',
    cuisine: 'izraelska',
    tag: 'crispy chicken',
    image: '/recipes/schnitzel-sezam.webp',
    intro: 'Cienki kurczak w chrupiącej panierce z sezamem. Prosty pewniak, ale cytryna i tahini robią go mniej nudnym.',
    whenToMake: 'Dla dzieci, dla dorosłych, dla ludzi, którzy mówią „zjadłbym coś chrupiącego”.',
    servings: 2,
    effort: 'średnio',
    dietTags: ['high-protein', 'comfort', 'dla dzieci'],
    collections: ['po-pracy'],
    ingredients: [
      ing({ amount: 2, name: 'filety z kurczaka', key: 'kurczak', scalable: true }),
      ing({ amount: 1, name: 'jajko', key: 'jajko', scalable: true }),
      ing({ amount: 60, unit: 'g', name: 'bułki tartej', key: 'bułka tarta', scalable: true }),
      ing({ name: 'sezam', key: 'sezam', scalable: false }),
      ing({ name: 'cytryna', key: 'cytryna', scalable: false }),
    ],
    steps: [
      'Rozbij kurczaka cienko.',
      'Panieruj w jajku, bułce i sezamie.',
      'Smaż do złotej panierki.',
      'Podaj z cytryną i prostą sałatką.',
    ],
    tip: 'Cienki filet smaży się szybko i nie wysusza. Gruby schnitzel to już kompromis moralny.',
  },
  {
    slug: 'charoset-daktyle-orzechy',
    title: 'Charoset z daktylami i orzechami',
    time: '12 min',
    minutes: 12,
    mood: 'fresh',
    cuisine: 'izraelska',
    tag: 'sweet paste',
    image: '/recipes/charoset-daktyle-orzechy.webp',
    intro: 'Daktyle, jabłko, orzechy i cynamon w słodkiej paście. Działa jako dodatek, deser albo smarowidło do chałki.',
    whenToMake: 'Kiedy chcesz coś słodkiego bez pieczenia i bez wielkiej cukierniczej ambicji.',
    servings: 4,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'bez glutenu'],
    collections: ['15-min'],
    ingredients: [
      ing({ amount: 120, unit: 'g', name: 'daktyli', key: 'daktyle', scalable: true }),
      ing({ amount: 1, name: 'jabłko', key: 'jabłko', scalable: true }),
      ing({ amount: 40, unit: 'g', name: 'orzechów włoskich', key: 'orzechy', scalable: true }),
      ing({ name: 'cynamon', key: 'cynamon', scalable: false }),
      ing({ name: 'sok z cytryny', key: 'cytryna', scalable: false }),
    ],
    steps: [
      'Posiekaj daktyle, jabłko i orzechy.',
      'Dopraw cynamonem i cytryną.',
      'Rozgnieć albo krótko zmiksuj.',
      'Schłódź przed podaniem.',
    ],
    tip: 'Nie miksuj na idealny krem. Trochę tekstury ratuje to przed dziecięcą papką.',
  },
  {
    slug: 'bourekas-feta-szpinak',
    title: 'Bourekas ze szpinakiem i fetą',
    time: '32 min',
    minutes: 32,
    mood: 'comfort',
    cuisine: 'izraelska',
    tag: 'puff pastry',
    image: '/recipes/bourekas-feta-szpinak.webp',
    intro: 'Ciasto francuskie, feta, szpinak i sezam. Chrupiące trójkąty, które znikają szybciej niż plan „zjem tylko jeden”.',
    whenToMake: 'Na gości, piknik albo szybkie ciepłe śniadanie.',
    servings: 4,
    effort: 'średnio',
    dietTags: ['bezmięsne', 'comfort'],
    collections: ['na-gosci', 'na-gosci'],
    ingredients: [
      ing({ amount: 1, unit: 'opakowanie', name: 'ciasta francuskiego', key: 'ciasto francuskie', scalable: true }),
      ing({ amount: 150, unit: 'g', name: 'szpinaku', key: 'szpinak', scalable: true }),
      ing({ amount: 120, unit: 'g', name: 'fety', key: 'feta', scalable: true }),
      ing({ amount: 1, name: 'jajko', key: 'jajko', scalable: true }),
      ing({ name: 'sezam', key: 'sezam', scalable: false }),
    ],
    steps: [
      'Podsmaż szpinak i odciśnij wodę.',
      'Wymieszaj z fetą.',
      'Napełnij kwadraty ciasta i złóż w trójkąty.',
      'Posmaruj jajkiem, posyp sezamem i piecz.',
    ],
    tip: 'Odciśnięty szpinak to różnica między chrupiącym bourekasem a mokrą kopertą.',
  },
  {
    slug: 'matbucha-papryka',
    title: 'Matbucha z papryką',
    time: '45 min',
    minutes: 45,
    mood: 'comfort',
    cuisine: 'izraelska',
    tag: 'slow relish',
    image: '/recipes/matbucha-papryka.webp',
    intro: 'Pomidory i papryka duszone długo z czosnkiem. Pasta, sos, dodatek do jajek albo mezze. Uniwersalny słoik dobra.',
    whenToMake: 'Gdy masz dużo papryki i chcesz przygotować coś, co poprawia kilka kolejnych posiłków.',
    servings: 4,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'bez glutenu', 'budżetowo'],
    collections: ['meal-prep', 'rozgrzewa'],
    ingredients: [
      ing({ amount: 3, name: 'papryki', key: 'papryka', scalable: true }),
      ing({ amount: 1, unit: 'puszka', name: 'pomidorów', key: 'pomidor', scalable: true }),
      ing({ amount: 3, unit: 'ząbki', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ name: 'chilli', key: 'chilli', scalable: false }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Pokrój paprykę i czosnek.',
      'Duś z pomidorami, oliwą i chilli.',
      'Gotuj długo, aż odparuje i zgęstnieje.',
      'Podawaj na ciepło albo zimno.',
    ],
    tip: 'Matbucha potrzebuje czasu, nie techniki. Nie kończ jej, gdy wygląda jak rzadki sos.',
  },
  {
    slug: 'hummus-msabbaha',
    title: 'Hummus msabbaha',
    time: '20 min',
    minutes: 20,
    mood: 'fresh',
    cuisine: 'izraelska',
    tag: 'warm hummus',
    image: '/recipes/hummus-msabbaha.webp',
    intro: 'Ciepła ciecierzyca, tahini, cytryna i oliwa. Bardziej rustykalny kuzyn hummusu, mniej gładki, bardziej obiadowy.',
    whenToMake: 'Na szybki lunch z pitą albo jako mezze, które faktycznie syci.',
    servings: 2,
    effort: 'lekko',
    dietTags: ['bezmięsne', 'high-protein', 'bez glutenu'],
    collections: ['15-min', 'po-pracy'],
    ingredients: [
      ing({ amount: 1, unit: 'puszka', name: 'ciecierzycy', key: 'ciecierzyca', scalable: true }),
      ing({ amount: 2, unit: 'łyżki', name: 'tahini', key: 'tahini', scalable: true }),
      ing({ amount: 0.5, name: 'cytryny', key: 'cytryna', scalable: true }),
      ing({ amount: 1, unit: 'ząbek', name: 'czosnku', key: 'czosnek', scalable: true }),
      ing({ name: 'oliwa', key: 'oliwa', scalable: false }),
    ],
    steps: [
      'Podgrzej ciecierzycę z odrobiną wody.',
      'Część rozgnieć, część zostaw w całości.',
      'Dodaj tahini, cytrynę i czosnek.',
      'Podaj ciepłe z oliwą.',
    ],
    tip: 'Nie rób z tego idealnie gładkiej pasty. Całe ziarna są tu częścią uroku.',
  },
]

export const regionalRecipes: Recipe[] = regionalRecipeEntries
